openapi: 3.1.0
    info:
      title: C2-02 Proof-of-Contribution API
      version: "1.0.0"
      description: >
        OpenAPI specification for the Proof-of-Contribution. This spec is contracts-first and
        references the canonical production API base at https://api.coherosphere.io.
    servers:
      - url: https://api.coherosphere.io
        description: Production environment
      - url: https://staging.api.coherosphere.io
        description: Staging environment
      - url: http://localhost:8080
        description: Local development

    paths:

/v1/poc/contributions:
  get:
    summary: Submit or list contributions
    responses:
      '200':
        description: OK
