openapi: 3.1.0
info:
info:
  title: C2-11 Public API Gateway
  version: "1.0.0"
  x-c2-id: C2-11
  description: Unified ingress (REST/gRPC/GraphQL) for internal services.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
servers:
  - url: https://api.coherosphere.io
    description: Production
  - url: https://staging.api.coherosphere.io
    description: Staging
paths: {}
components: {}
