extends:
  - "spectral:oas"

rules:
  # Keep hard failures on broken OpenAPI structure
  oas3-schema: error
  oas3-valid-schema-example: error
  operation-operationId-unique: error
  path-params: error
  operation-2xx-response: error
  no-ambiguous-paths: error

  # Helpful, but only warn (won't fail CI)
  info-contact: warn
  info-description: warn
  info-license: warn
  tags-alphabetical: warn
  operation-tag-defined: warn
  servers-no-trailing-slash: warn

  # Optional: quiet down noisy style nits
  operation-description: warn
  operation-operationId: warn
  operation-summary: warn
