openapi: 3.1.0
info:
  title: C2-09 — Knowledge API
  version: 0.1.0
  x-c2-id: C2-09
servers:
  - url: https://api.coherosphere.io
    description: Production
  - url: https://staging.api.coherosphere.io
    description: Staging
paths: {}
components: {}
