name: Deploy Docusaurus

on:
  push:
    branches: [ main ]
    paths:
      - "docs.coherosphere.io/**"
      - ".github/workflows/deploy-docs.yml"
      - "assets/docs/**"
      - "packages/docs/**"
  workflow_dispatch: {}

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    defaults:
      run:
        working-directory: docs.coherosphere.io   # <- Ordner deines Docusaurus-Projekts

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: docs.coherosphere.io/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build site
        run: npm run build

      # CNAME in den Output legen (wichtig für Custom Domain)
      - name: Add CNAME
        run: echo "docs.coherosphere.io" > build/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
