name: Validate Event Schemas (JSON)

on:
  push:
    paths:
      - "assets/specs/events/*.json"
      - ".github/workflows/validate-event-schemas.yml"
  pull_request:
    paths:
      - "assets/specs/events/*.json"
  workflow_dispatch: {}

jobs:
  jsonschema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install jsonschema==4.23.0
      - name: Lint all schemas
        run: |
          python - <<'PY'
          import json, glob, sys
          from jsonschema import Draft202012Validator
          errs = []
          for f in glob.glob("assets/specs/events/*.json"):
            try:
              schema = json.load(open(f))
              Draft202012Validator.check_schema(schema)
            except Exception as e:
              errs.append((f, str(e)))
          if errs:
            for f,e in errs: print(f"ERR {f}: {e}")
            sys.exit(1)
          print("All JSON Schemas valid.")
          PY
