name: Validate OpenAPI Domains Syntax & Structure

on:
  push:
    paths:
      - "assets/specs/openapi/**/*.yaml"
      - "assets/specs/openapi/**/*.yml"
      - ".github/workflows/validate-openapi.yml"
  pull_request:
    paths:
      - "assets/specs/openapi/**/*.yaml"
      - "assets/specs/openapi/**/*.yml"
      - ".github/workflows/validate-openapi.yml"

jobs:
  validate-openapi:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Strikte OpenAPI-Syntax/Struktur-Validierung
      - name: Swagger Editor Validate
        uses: char0n/swagger-editor-validate@v1
        with:
          files: |
            assets/specs/openapi/**/*.yaml
            assets/specs/openapi/**/*.yml

      # 2) Linting (nur Severity "error" bricht ab; warnings sind ok)
      - name: Spectral Lint
        uses: stoplightio/spectral-action@v0
        with:
          file_glob: "assets/specs/openapi/**/*.yaml"
          fail_severity: "error"

      # 3) Kompakter Summary-Output
      - name: Summarize
        if: always()
        run: |
          echo "OpenAPI syntax & structure validation finished." >> $GITHUB_STEP_SUMMARY
