name: Validate Codegen – Contracts (Prism + Schemathesis)

on:
  workflow_dispatch: {}
  push:
    paths:
      - "assets/specs/openapi/**"
      - ".github/workflows/validate-codegen-contracts.yml"
      - "scripts/codegen_contracts_validate.sh"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  contracts:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install CLI deps (Prism, Redocly, Schemathesis, PyYAML)
        run: |
          npm i -g @stoplight/prism-cli@5 @redocly/cli@latest
          python -m pip install --upgrade pip
          pip install "schemathesis>=3.27" pyyaml

      - name: Make script executable
        run: chmod +x scripts/codegen_contracts_validate.sh

      - name: Run contracts harness (bundle → prism → schemathesis)
        env:
          PORT_BASE: "41000"
          STRICT_CONTRACTS: "false"  # auf "true" setzen, falls Specs ohne paths als Fehler gelten sollen
        run: |
          bash scripts/codegen_contracts_validate.sh assets/specs/openapi

      - name: Upload logs & reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codegen-contracts-artifacts
          path: |
            .harness_logs_contracts
            .harness_out_contracts
            .harness_tmp/bundled
