name: Validate Codegen

on:
  workflow_dispatch: {}
  push:
    paths:
      - "assets/specs/openapi/**/*.yaml"
      - "assets/specs/openapi/**/*.yml"
      - "scripts/codegen_harness.sh"
      - ".github/workflows/validate-codegen.yml"
  pull_request:
    paths:
      - "assets/specs/openapi/**/*.yaml"
      - "assets/specs/openapi/**/*.yml"
      - "scripts/codegen_harness.sh"
      - ".github/workflows/validate-codegen.yml"

jobs:
  codegen:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # Codegen-Only: Prism im Harness deaktivieren (kann auf soft/strict gestellt werden)
    env:
      PRISM_MODE: "off"   # off | soft | strict
      OPENAPI_ROOT: "assets/specs/openapi"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Make harness executable
        run: chmod +x scripts/codegen_harness.sh

      - name: Run codegen harness (SDK build sanity)
        run: bash scripts/codegen_harness.sh "$OPENAPI_ROOT"

      - name: Upload harness artifacts (SDKs + logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codegen_harness_artifacts
          path: |
            .harness_out/**
            .harness_logs/**
            .harness_tmp/**
          if-no-files-found: ignore
